# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'f2e73650-0335-40f1-ad00-e87198d03232'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName webarmdep -linkedTemplateUri https://raw.githubusercontent.com/kathirt/AzureRMPipeline-repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
